In [8]:
# Importing libraries/modules
import sys
import os
import numpy as np

# Adding the path to the parent directory of trans_polytope_repr
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

from trans_polytope_repr import *

The main theorem in [De Loera and Onn, 2006] states the following:

__Theorem 1.1__ 

Any rational polytope $P=\{y\in \R_{\geq 0}^{n}: Ay=b\}$ is polynomial-time representable as a "slim" 3-way transportation polytope, i.e., of smallest possible depth three:
$$T = \{x\in \R_{\geq 0}^{r\times c\times 3}:\sum_{i}x_{i,j,k}=w_{j,k}, \sum_{j}x_{i,j,k}=v_{i,k}, \sum_{k}x_{i,j,k}=u_{ij}\}$$ 
for which there is an injection $\sigma:\{[n]\to [r]\times [c]\times [3]\}$ such that the coordinate-erasing projection
$$\pi:\R^{r\times c \times 3}\to \R^n: x\mapsto \pi(x)=(x_{\sigma(1)}, \ldots, x_{\sigma(n)}) \$$
provides a bijection between $P$ and $T$, and between their integer points.

Given a polytope $P=\{y\in \R_{\geq 0}^{n}: Ay=b\}$ the function `slim_line_sum_representation` from `trans_polytope_repr`, takes an array $M=[A|b]$ (obtained by concatenating the vector $b$ to the matrix $A$) as an input, as well as an upper bound on the entries of the polytope $P$, which is assumed to be known by the user. It will return an object with attributes `U,V,W` which correspond to the $\{1,2\}$, $\{1,3\}$ and $\{2,3\}$ 2-margins, respectively, defining the transportation polytope $T$. 

In [11]:
# Example
# We consider the polytope P = {(x_1, x_2, x_3) >= 0 : x_1 - 2x_2 = 0, x_2 + x_3 = 1}
# which has defining matrix A = [[1, -2, 0], [0, 1, 1]] and b = [0, 1]
A = np.array([[1,-2,0], [0,1,1]])
b = np.array([0, 1])
M = np.column_stack((A, b))
entries_upper_bound = 2

T = slim_line_sum_representation(M, entries_upper_bound)

print(f"[12] 2-margin | dimensions: {T.U.shape}")
print(T.U, "\n")

print(f"[13] 2-margin | dimensions: {T.V.shape}")
print(T.V, "\n")

print(f"[23] 2-margin | dimensions: {T.W.shape}")
print(T.W, "\n")

[12] 2-margin | dimensions: (16, 11)
[[2. 0. 2. 2. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 2. 0. 0. 2. 0. 0. 0.]
 [0. 2. 0. 0. 2. 0. 0. 0. 2. 0. 0.]
 [2. 0. 0. 0. 2. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 2. 0. 2. 0. 0. 0.]
 [2. 0. 0. 0. 0. 2. 0. 0. 2. 0. 0.]
 [0. 0. 2. 0. 0. 2. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 2. 0.]
 [0. 2. 2. 0. 0. 0. 2. 0. 0. 0. 2.]] 

[13] 2-margin | dimensions: (16, 3)
[[2. 4. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 4. 2.]] 

[23] 2-margin | dimensions: (11, 3)
[[4. 2. 0.]
 [1. 3. 0.]
 [3. 3. 0.]
 [6. 0. 2.]
 [6. 0. 2.]
 [6. 0. 2.]
 [6. 0. 2.]
 [0. 2. 6.]
 [0. 2. 6.]
 [0. 2. 6

As we can see, in this particular example $T\subset \R^{16\times 11\times 3}$. Given an integer point in the original polytope $y\in P$, one can retrieve the image $x=\pi(y)\in T$ described in Theorem 1.1 by using the function `embed_in_line_sum`. 

In [12]:
# The following is an integer point in the polytope P = {(x_1, x_2, x_3) >= 0 : x_1 - 2x_2 = 0, x_2 + x_3 = 1} we considered above
y = np.array([2,1,0])
x = embed_in_line_sum(y, M, entries_upper_bound)

print("Embedding of y into T: ")
print(x['point'])

Embedding of y into T: 
[[[2. 0. 0.]
  [0. 0. 0.]
  [0. 2. 0.]
  [0. 0. 2.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 2. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [2. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 2.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [2. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 2.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [2. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 2.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [2. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 2.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [1. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 1. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [1. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  

The result in Theorem 1.1 relies in 3 stages that are described below, along with the functions implemented to explore each of the stages. Before going into details we remind the following general definition introduced in the paper.

A polytope $P\subset \R^p$ is __representable__ as a polytope $Q\subset \R^q$ if there exists an injection $\sigma:\{1, \ldots, p\}\to \{1, \ldots, q\}$ such that the coordinate-erasing projection 
$$
\pi:\R^q\to \R^p : x= (x_1, \ldots, x_q) \mapsto \pi(x) = (x_{\sigma(1)}, \ldots, x_{\sigma(p)})
$$
provides a bijection between $Q$ and $P$, and between the sets of integer points $Q\cap \Z^q$ and $P\cap \Z^p$.

#### Stage 1. Preprocessing: Coefficient Reduction

__Lemma 3.1__ [De Loera and Onn, 2006] Any rational polytope $P= \{y\geq 0: Ay =b\}$ is polynomial-time representable as a polytope $Q=\{x\geq 0 : Cx=d\}$ with $\{-1, 0, 1, 2\}$-valued defining matrix $C$.

The function `prep_rep` takes takes a standard representation of a polytope $P= \{y\geq 0: Ay =b\}$ as an array $[A|b]$ and returns the matrix $[C|d]$ encoding the polytope $Q$ in lemma 3.1 

In [7]:
# Example
# We consider the polytope P = {(x_1, x_2, x_3) >= 0 : x_1 - 5x_2 = 0, x_2 + x_3 = 1}
# which has defining matrix A = [[1, -5, 0], [0, 1, 1]] and b = [0, 1]
A = np.array([[1,-5,0,0], [0,1,1,1]])
b = np.array([0, 1])
P_array = np.column_stack((A, b))

# We recover a representation with {-1,0,1,2}-valued defining matrix C and defining vector d
Q_array = prep_rep(P_array)
print("New defining matrix:")
print(Q_array[:, :-1], "\n")
print(f"New defining vector: {Q_array[:, -1]}")


New defining matrix:
[[ 0  2 -1  0  0  0]
 [ 0  0  2 -1  0  0]
 [ 1 -1  0 -1  0  0]
 [ 0  1  0  0  1  1]] 

New defining vector: [0 0 0 1]


#### Stage 2. Representing polytopes as plane-sum entry-forbidden transportation polytopes

__Theorem 3.2__ [De Loera and Onn, 2006] Any rational polytope $P= \{y\geq 0: Ay =b\}$ is polynomial-time representable as a plane-sum entry-forbidden 3-way transportation polytope 
$$
T = \{x\in \R_{\geq 0}^{r\times r\times h}: x_{i,j,k}=0 \text{ for all }(i,j,k)\notin E, \text{ and } \sum_{i,j}x_{i,j,k}=w_k, \sum_{i,k}x_{i,j,k}=v_j, \sum_{i,j}x_{i,j,k}=u_i\}.
$$
Where $E$ is referred as the set of __enabled__ entried of the polytope.

The function `as_plane_sum` takes a standard representation of a polytope $P= \{y\geq 0: Ay =b\}$ as an array $[A|b]$, along with an upper bound for the entries of the polytope. It returns a `plane_sum_entry_forbidden` object with the following attributes that define the transportation polytope $T$ in theorem 3.2
* `u`: \{1\} 1-margin of $T$ 
* `v`: \{2\} 1-margin of $T$ 
* `w`: \{3\} 1-margin of $T$ 
* `E`: Set of enabled entries in the transportation polytope $T$

In [23]:
# Using Q_array from the previous code cell 
T_plane_sum = as_plane_sum(Q_array, 2)
print("[1]-marging:", T_plane_sum.u, "\n")
print("[2]-marging:", T_plane_sum.v, "\n")
print("[3]-marging:", T_plane_sum.w, "\n")
print("[Enabled entries:", T_plane_sum.Enabled, "\n")

[1]-marging: [2 2 2 2 2 2 2 2 2 2] 

[2]-marging: [2 2 2 2 2 2 2 2 2 2] 

[3]-marging: [ 2  2  4  1 11] 

[Enabled entries: [[0, 0, 2], [0, 0, 4], [1, 1, 0], [2, 2, 0], [3, 3, 3], [3, 1, 2], [1, 2, 4], [2, 3, 4], [4, 4, 1], [5, 5, 1], [5, 4, 0], [4, 5, 4], [6, 6, 4], [7, 7, 4], [7, 6, 1], [6, 7, 2], [8, 8, 3], [8, 8, 4], [9, 9, 3], [9, 9, 4]] 



__Theorem 3.3__ [De Loera and Onn, 2006] Any rational plane-sum entry-bounded 3-way transportation polytope 
$$
P = \{y\in \R^{l\times m \times n}_{\geq 0}: \sum_{i,j}y_{i,j,k}=c_k, \sum_{i,k}y_{i,j,k}=b_j, \sum_{j,k}y_{i,j,k}=a_i, y_{i,j,k}\leq e_{i,j,k}\}
$$
is strongly-polynomial-time representable as a line-sum slim transportation polytope
$$
T=\{x\in \R^{r\times c \times 3}_{\geq 0}: \sum_{I}x_{I,J,K}=w_{J, K}, \sum_{J}x_{I,J,K}=v_{I,K}, \sum_{K}x_{I,J,K}=u_{I,J}\}.
$$

The function `as_line_sum` takes a `plane_sum_entry_forbidden` object (encoding a plane-sum transportation polytope with forbidden entries) as input and returns a `slim_line_sum` object with the following attributes that define the transportation polytope $T$ in theorem 3.3
* `U`: \{1,2\} 2-margin of $T$ 
* `V`: \{1,3\} 2-margin of $T$ 
* `W`: \{2,3\} 2-margin of $T$ 

In [28]:
# Using T_plane_sum from the previous code cell 
T_line_sum = as_slim_line_sum(T_plane_sum)
print("[1,2]-marging:\n", T_line_sum.U, "\n")
print("[1,3]-marging:\n", T_line_sum.V, "\n")
print("[2,3]-marging:\n", T_line_sum.W, "\n")


[1,2]-marging:
 [[0. 0. 2. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 2.]] 

[1,3]-marging:
 [[2. 4. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 0. 2.]
 [2. 2. 2.]
 [2. 2